[general]
import = [
    "./colorscheme.toml"
]
[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true

[window.padding]
x = 5
y = 5

[font]
size = 15.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Medium"
